buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.7.0"
    }
}

repositories {
    google()
    mavenLocal()
    mavenCentral()
}

apply plugin: "com.android.application"

def AAVersion = "4.9.0-SNAPSHOT" // change this to your desired version, for example the latest stable: 4.8.0
dependencies {
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    implementation "org.androidannotations:androidannotations-api:$AAVersion"
}

android {
    namespace "org.androidannotations.sample"
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 35

        // If you have different applicationIds for buildTypes or productFlavors uncomment this block.
        //javaCompileOptions {
        //    annotationProcessorOptions {
        //        arguments = ['resourcePackageName': "org.androidannotations.sample"]
        //    }
        //}
    }
}
